### ISSUE TITLE
Heating Energy Consumed is not updating automatically

### ISSUE THREAD

**Issue by rednas201** [msvisser/remeha_home#88]
Since this morning (12-2-2025), the Heating Energy Consumed sensor is stuck at 0, since it resets every midnight. 
Only when I reboot Home Assistant, the sensor retrieves the actual value of consumed energy. 
In the Remeha app, there is actually energy consumed. 
Other sensors, like the current thermostat temperature is updating. 
Since this issue appeared at the same time as #87, these might be related.

**Comment by msvisser** [comment]
Unfortunately the missing outdoor temperature completely broke the integration. I have released [v0.1.17](https://github.com/msvisser/remeha_home/releases/tag/v0.1.17) which fixes these issues.

**Comment by Ardvark99Nl** [comment]
I have the same issue since yesterday, and also the outdoor temperature sensor is stuck. For the energy sensors, reload of the integration is enough.

**Comment by rednas201** [comment]
I solved the issue by disabling the outdoor sensor. 
Thanks for the quick update. One sidenote: for v0.1.17, home assistant 2025.1.4  is the minimum required version. Does it really have to be that one? 
I'm still on a 2024 version due to older hardware and can't download the update.

**Comment by msvisser** [comment]
I bumped the Home Assistant version because I was having issues with the older version in my development container, but I don't see reason why the 2025 version would be required. Is the change preventing you from updating the integration?

**Comment by Ardvark99Nl** [comment]
I still have the same issuer with the sensor in 0.1.17. Tried to restart HA, disabling and enabling the sensor again, and reloading the integration, but the entity stays not available.

![Image](https://github.com/user-attachments/assets/9f8d0ccd-a633-48e1-9241-2b213ac1a8b6)

**Comment by msvisser** [comment]
I think that because of the change in the key, a new entity is created for the outdoor temperature. Please check the device if there is a new outdoor temperature entity. You can remove the old entity and rename the id of the new entity.

**Edit:** Some more technical info, the entity `unique_id` is determined by the following three items: `DOMAIN`, `self.item_id`, and `entity_description.key`. In this case `DOMAIN` is `remeha_home`, `self.item_id` is the appliance UUID, and `entity_description.key` is the field used for the sensor. Because I changed the key, Home Assistant no longer sees them as the same entity. It is a bit unfortunate, but not something I can easily fix without refactoring a bunch of code.

**Comment by Ardvark99Nl** [comment]
> I think that because of the change in the key, a new entity is created for the outdoor temperature. Please check the device if there is a new outdoor temperature entity. You can remove the old entity and rename the id of the new entity.

Yes, in deed, didn't see the new entity at first, but now it's available. Thanks

**Comment by rednas201** [comment]
@msvisser it indeed prevents me from updating. I had a lot of performance issues on the 2024.9 versions and later, so I stayed with 2024.7. 
It would not see why this wouldn't work on an earlier version of Home Assistant.
